<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-N8OU8L6" ignored="0" name="RetryFailedTestCases" tests="8" failures="2" timestamp="24 Dec 2020 06:01:07 GMT" time="0.115" errors="0">
  <testcase name="TC1" time="0.016" classname="Org.testcases.TestNGRetryFeature"/>
  <testcase name="TC5" time="0.001" classname="Org.testcases.TestNGRetry"/>
  <testcase name="TC6" time="0.001" classname="Org.testcases.TestNGRetry"/>
  <testcase name="TC7" time="0.006" classname="Org.testcases.TestNGRetry">
    <skipped/>
  </testcase> <!-- TC7 -->
  <testcase name="TC7" time="0.001" classname="Org.testcases.TestNGRetry">
    <skipped/>
  </testcase> <!-- TC7 -->
  <testcase name="TC7" time="0.002" classname="Org.testcases.TestNGRetry">
    <skipped/>
  </testcase> <!-- TC7 -->
  <testcase name="TC7" time="0.001" classname="Org.testcases.TestNGRetry">
    <failure type="java.lang.AssertionError" message="Assertion message expected [expecting] but found [actual]">
      <![CDATA[java.lang.AssertionError: Assertion message expected [expecting] but found [actual]
at Org.testcases.TestNGRetry.TC7(TestNGRetry.java:22)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- TC7 -->
  <testcase name="TC7" time="0.059" classname="Org.testcases.TestNGRetry">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at Org.Base.BaseClass.captureScreenshot(BaseClass.java:59)
at TestListeners.TestNGListener.onTestFailure(TestNGListener.java:25)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- TC7 -->
</testsuite> <!-- RetryFailedTestCases -->
