<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="3" hostname="DESKTOP-N8OU8L6" name="Org.testcases.TestNGRetry" tests="7" failures="1" timestamp="15 Dec 2020 14:49:31 GMT" time="0.030" errors="0">
  <testcase name="TC5" time="0.010" classname="Org.testcases.TestNGRetry"/>
  <testcase name="TC7" time="0.009" classname="Org.testcases.TestNGRetry">
    <skipped/>
  </testcase> <!-- TC7 -->
  <testcase name="TC6" time="0.002" classname="Org.testcases.TestNGRetry"/>
  <testcase name="TC8" time="0.004" classname="Org.testcases.TestNGRetry"/>
  <testcase name="TC7" time="0.002" classname="Org.testcases.TestNGRetry">
    <skipped/>
  </testcase> <!-- TC7 -->
  <testcase name="TC7" time="0.001" classname="Org.testcases.TestNGRetry">
    <skipped/>
  </testcase> <!-- TC7 -->
  <testcase name="TC7" time="0.002" classname="Org.testcases.TestNGRetry">
    <failure type="java.lang.AssertionError" message="Assertion message expected [expecting] but found [actual]">
      <![CDATA[java.lang.AssertionError: Assertion message expected [expecting] but found [actual]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at Org.testcases.TestNGRetry.TC7(TestNGRetry.java:21)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.retryFailed(Invoker.java:838)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1009)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- TC7 -->
</testsuite> <!-- Org.testcases.TestNGRetry -->
